package org.openmrs.module.ehospitalws.web.constants;

public class SharedConcepts {
    public static final String WEIGHT_UUID = "5089AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    public static final String HEIGHT_UUID = "5090AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    public static final String BMI_UUID = "1342AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    public static final String TEMPERATURE_UUID = "5088AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    public static final String DIASTOLIC_BLOOD_PRESSURE_UUID = "5086AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    public static final String SYSTOLIC_BLOOD_PRESSURE_UUID = "5085AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    public static final String PULSE_RATE_UUID = "5087AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    public static final String IMPRESSION_DIAGNOSIS_CONCEPT_UUID = "759bf916-5549-4fe1-a588-a399ba04dfd5";
}
